name: Alerta de inactividad de commits

on:
  schedule:
    # Cada hora entre 08:00 y 20:00 hora de España (CET)
    - cron: "0 8-20 * * *"  # UTC
  workflow_dispatch:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    outputs:
      no_commits: ${{ steps.check_commits.outputs.no_commits }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Comprobar commits recientes
        id: check_commits
        run: |
          echo "Buscando commits de la última hora..."
          recent_commits=$(git log --since="5 hours ago" --oneline)
          if [ -n "$recent_commits" ]; then
            echo "commits_recentes=true" >> $GITHUB_ENV
            echo "no_commits=false" >> $GITHUB_OUTPUT
          else
            echo "commits_recentes=false" >> $GITHUB_ENV
            echo "no_commits=true" >> $GITHUB_OUTPUT
          fi
 
      - name: Enviar alerta si no hay commits recientes
        if: steps.check_commits.outputs.no_commits == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: " L’aplicació TEMPS no funciona correctament."
          body: "No s’han detectat commits recents. L’aplicació TEMPS no funciona correctament. No s’ha generat cap fitxer XML des de fa  mes de una hora a GitHub ."
          to: ${{ secrets.ALERT_EMAIL }}
          from: "GitHub Bot <${{ secrets.GMAIL_USER }}>"
